#!/bin/sh


# HELP AN USAGE

SCRIPTNAME="$(basename $0)"
VERSION="0.3.2-sh"

version() {
	echo "telegram.sh $VERSION"
	if [ "$1" = "full" ]; then
		echo "
 A telegram client to work on simple sh shell
   https://github.com/lulis/telegram.sh

 Based on original telegram.sh by Fabian Schlenz"
	fi
}

help_usage() {
	version
	echo '
 Usage: '$SCRIPTNAME' [options]
 Options:
   -m <text>      Message text to send
   -              Get message from STDIN
   -f <file>      Send a file
   -i <file>      Send a file as image
   -T <title>     Title of the message
   -t <token>     Your telegram bot token
   -c <chat_id>   Chat to send message
   -l             List known chat_ids for current token
   -M             Enables Markdown processing
   -H             Enables HTML processing
   -C             Send text as monospace code
   -D             Disable link preview on text messages
   -N             Send message without notification sound
   -n             Dry-run: do not send, only print
   -v             Verbose mode
   -h, --help     This help
   --bot          Show info about creating a bot
   --config       Show info about configuration files
   --version      Show version info'
	exit $1
}

help_bot() {
	version
	echo '
 To create a new bot on Telegram:

  * Search for the user @botfather and start to chat
  * Create a new bot sending /newbot
  * Keep the given token (and keep it secret!)
  * Send any message to your new bot to activate it
  * Find your chat_id running: '$SCRIPTNAME' -t <token> -l

 You now have your token and your chat_id, try it:
  '$SCRIPTNAME' -t <token> -c <chat_id> -m "Hello there!"

 See also: '$SCRIPTNAME' --config'
	exit $1
}

help_config() {
	version
	echo '
 You can define <token> and <chat_id> by:

  1. Command line options: -t <token> -c <chat_id>
  2. Environment variables: TELEGRAM_TOKEN and TELEGRAM_CHAT
  3. User-based config file: ~/.telegram-sh.conf
  4. Global config file: /etc/telegram-sh.conf

 The earliest take precedence, so you can define general <token> in
 ~/telegram-sh.conf and then overwrite it using -t on command line.

 Config file contents should be like:

TOKEN=123456:AbcDefGhi-JlkMno
CHAT_ID=12345678

 See also: '$SCRIPTNAME' --bot'
	exit $1
}


# DEPENDENCIES

for i in curl grep awk cut wc; do
	if ! [ -x "$(command -v $i)" ]; then missingDep="$missingDep $i"; fi
done
[ -n "$missingDep" ] && { echo "Please install required dependencies: $missingDep"; exit 1; }


# DEFINES

TOKEN=""
CHAT=""
DEBUG=false
DRY_RUN=false
IMAGE_FILE=""
DOCUMENT_FILE=""
PARSE_MODE=""
CODE_MODE=0
ACTION=""
TITLE=""
DISABLE_WEB_PAGE_PREVIEW=false
DISABLE_NOTIFICATION=false

URL="https://api.telegram.org/bot"
FILE_URL="https://api.telegram.org/file/bot"
CURL_OPTIONS="-s"


# based on https://stackoverflow.com/a/38607019
json_console() {
	echo -n "$1" | grep -Eo '"[^"]*" *(: *([0-9]*|"[^"]*")[^{}\["]*|,)?|[^"\]\[\}\{]*|\{|\},?|\[|\],?|[0-9 ]*,?' | \
	awk '{if ($0 ~ /^[]}]/) i--; j=0; while (j++<i) printf " "; printf "%s\n", $0; if ($0 ~ /^[[{]/) i++}'
}

# based on http://www.etalabs.net/sh_tricks.html
fnmatch() {
	case "$2" in $1) return 0 ;; *) return 1 ;; esac ;
}


list_chats() {
	log "$URL$TOKEN"
	response=`curl $CURL_OPTIONS $URL$TOKEN/getUpdates`
	log "$response"
	echo 'Look for your chat_id below, something like "chat":{"id":<CHAT_ID>.'
	echo "Verify also first_name, last_name and username."
	echo "If the chat is not listed, send a message to your bot and try again."
	json_console "$response"
}

log() {
	[ "$DEBUG" = true ] && echo "DEBUG: $1"
}

check_file() {
	if [ ! -e "$1" ]; then
		echo "The file $1 does not exist."
		exit 1
	fi

	size=$(wc -c < "$1")
	if [ "$size" -gt 52428800 ]; then
		echo "File $1 is bigger than Telegram bots limits (currently 50MB)."
		exit 1
	fi
}

ARGNUM="$#"
while [ "$#" -gt 0 ]; do
	case $1 in
		-t) TOKEN="$2"; shift 2 ;;
		-c) CHAT="$2"; shift 2 ;;
		-m) TEXT="$2"; shift 2 ;;
		-) TEXT="-"; shift ;;
		-i) IMAGE_FILE="$2"; shift 2 ;;
		-f) DOCUMENT_FILE="$2"; shift 2 ;;
		-T) TITLE="$2"; shift 2 ;;
		-M) PARSE_MODE="Markdown"; shift ;;
		-H) PARSE_MODE="HTML"; shift ;;
		-C) PARSE_MODE="Markdown"; CODE_MODE=1; shift ;;
		-l) ACTION="list_chats"; shift ;;
		-v) DEBUG=true; shift ;;
		-n) DRY_RUN=true; shift ;;
		-D) DISABLE_WEB_PAGE_PREVIEW=true; shift ;;
		-N) DISABLE_NOTIFICATION=true; shift ;;
		-h|--help) help_usage 0 ;;
		--bot) help_bot 0 ;;
		--config) help_config 0 ;;
		--version) version full ; exit ;;
		-?|*) echo "Invalid option: '$1' \nUse $SCRIPTNAME -h for help." ; exit 1 ;;
		esac
done

log "Option TOKEN is '$TOKEN'"
log "Option CHAT is '$CHAT'"

log "Importing env vars..."
[ -z "$TOKEN" ] && { TOKEN=$TELEGRAM_TOKEN; log "TOKEN is '$TOKEN'"; }
[ -z "$CHAT" ] && { CHAT=$TELEGRAM_CHAT; log "CHAT is '$CHAT'"; }

log "Importing config files..."
for f in ~/.telegram-sh.conf /etc/telegram-sh.conf; do
	if [ -r $f ]; then
		log "Reading $f"
		[ -z "$TOKEN" ] && { TOKEN=$(cat "$f" | grep "^TOKEN=" | cut -d'=' -f2); log "TOKEN is '$TOKEN'"; }
		[ -z "$CHAT" ] && { CHAT=$(cat "$f" | grep "^CHAT_ID=" | cut -d'=' -f2); log "CHAT is '$CHAT'"; }
	fi
done

if [ -z "$TOKEN" ]; then
	echo "No bot token was given."
	exit 1
fi

if [ -z "$CHAT" ] && [ -z "$ACTION" ]; then
	echo "No chat given."
	exit 1
fi

if [ "$ACTION" = "list_chats" ]; then
	list_chats
	exit 0
fi

log "Text: $TEXT"

if [ "$TEXT" = "-" ] ; then
	TEXT=$(cat -)
fi

log "Text: $TEXT"

if [ $CODE_MODE -eq 1 ]; then
	TEXT='```'$'\n'$TEXT$'\n''```'
fi

log "Text: $TEXT"

if [ -n "$TITLE" ]; then
	if [ "$PARSE_MODE" = "HTML" ]; then
		TEXT="<b>$TITLE</b>"$'\n'"$TEXT"
	elif [ "$PARSE_MODE" = "Markdown" ]; then
		TEXT="*$TITLE*"$'\n'"$TEXT"
	else
		TEXT="$TITLE"$'\n'"$TEXT"
	fi
fi

if [ -z "$TEXT" ] && [ -z "$DOCUMENT_FILE" ] && [ -z "$IMAGE_FILE" ]; then
	echo "Message needs some text, image or file."
	exit 1
fi

if [ -n "$DOCUMENT_FILE" ] && [ -n "$IMAGE_FILE" ]; then
	echo "Can't send a file AND an image at the same time."
	exit 1
fi

[ -n "$PARSE_MODE" ] && CURL_OPTIONS="$CURL_OPTIONS --form-string parse_mode=$PARSE_MODE"
if [ -n "$DOCUMENT_FILE" ]; then
	check_file "$DOCUMENT_FILE"

	CURL_OPTIONS="$CURL_OPTIONS --form document=@$DOCUMENT_FILE"
	CURL_OPTIONS="$CURL_OPTIONS --form caption=<-"
	METHOD="sendDocument"
elif [ -n "$IMAGE_FILE" ]; then
	check_file "$IMAGE_FILE"
	CURL_OPTIONS="$CURL_OPTIONS --form photo=@$IMAGE_FILE"
	CURL_OPTIONS="$CURL_OPTIONS --form caption=<-"
	METHOD="sendPhoto"
else
	CURL_OPTIONS="$CURL_OPTIONS --form text=<-"
	[ "$DISABLE_WEB_PAGE_PREVIEW" = true ] && CURL_OPTIONS="$CURL_OPTIONS --form-string disable_web_page_preview=true"
	METHOD="sendMessage"
fi

[ "$DISABLE_NOTIFICATION" = true ] && CURL_OPTIONS="$CURL_OPTIONS --form-string disable_notification=true"

for id in "$CHAT"; do
	MY_CURL_OPTIONS="$CURL_OPTIONS --form-string chat_id=$id $URL$TOKEN/$METHOD"
	if [ "$DRY_RUN" = true ]; then
		echo "Executing: curl $MY_CURL_OPTIONS"
		echo "     Text: $TEXT"
		echo
		status=0
		response='{"ok": true}'
	else
		response=`echo "$TEXT" | curl $MY_CURL_OPTIONS`
		status=$?
	fi
	log "Response was: $response"
	if [ $status -ne 0 ]; then
		echo "curl reported an error. Exit code was: $status."
		echo "Response was: $response"
		echo "Quitting."
		exit $status
	fi

	if ! fnmatch '{"ok":true*' "$response" ; then
		echo "Telegram reported an error:"
		json_console "$response"
		echo "Quitting."
		exit 1
	fi
done
